---

-  hosts: all
   become: true
   tasks:
   
   -  name: update repo
      dnf:
        update_cache : yes
      when: ansible_distribution == "CentOS"

   -  name: install tomcat
      dnf:
        name: tomcat
        state: latest
      when: ansible_distribution == "CentOS"

   -  name: insatll httpd
      dnf:
        name: httpd
      when: ansible_distribution == "CentOS"

   -  name: install appache2
      apt:
        name: apache2
      when: ansible_distribution == "Ubuntu"
