---

-  hosts: all
   become: true
   tasks:

   -  name: remove tomcat
      dnf:
        name: tomcat
        state: absent
      when: ansible_distribution == "CentOS"

   -  name: remove httpd
      dnf:
        name: httpd
        state: absent
      when: ansible_distribution == "CentOS"

   -  name: update repo
      dnf:
        update_cache : yes
      when: ansible_distribution == "CentOS"
